logging:
  level:
    root: DEBUG
  path: /var/log/helios
server:
  port: 7000
spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    password: admin
    url: jdbc:oracle:thin:@192.168.3.67:1521:HELIOS
    username: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: oracle
  support-methods-arguments: true
  params: count=countSql
  offset-as-page-num: true
  row-bounds-with-count: true
  reasonable: true