logging:
  level:
    root: DEBUG
  path: /var/log/helios
server:
  port: 7000
spring:
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    password:  admin
    url: jdbc:oracle:thin:@192.168.2.45:1521:HELIOS
    username: snbaby
#让mybatis知道mapper在哪里
mybatis:
    mapper-locations: classpath:mapper/*.xml